version: "2.1"
services:
  live.ope.admin.app.no.wl:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ENV_SECURITY_API_URL=https://bovoyager.casinovip365.com/api/security-admin/v1
      - ENV_PLAYERS_API_URL=https://bovoyager.casinovip365.com/api/players/v1
      - ENV_USERS_API_URL=https://bovoyager.casinovip365.com/api/users/v1
      - ENV_WALLET_API_URL=https://bovoyager.casinovip365.com/api/wallet/v1
      - ENV_MULTILANGS_API_URL=https://bovoyager.casinovip365.com/api/multilanguage/v1
    ports:
      - "80"
    networks:
      - casinovip365__live.backend
networks:
  casinovip365__live.backend:
    external: true
